package app

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/gethasp/hasp/apps/server/internal/runtime"
)

// docsCommand handles `hasp docs <subcommand>`. Today only "markdown" is
// supported; the dispatch is wired through a small switch so future
// generators (man pages, html, json schema) can plug in without changing
// the root command inventory.
func docsCommand(ctx context.Context, args []string, stdout io.Writer, _ io.Writer) error {
	if len(args) == 0 {
		return errors.New("usage: hasp docs <markdown> [--out <path>]")
	}
	switch args[0] {
	case "markdown":
		return docsMarkdownCommand(ctx, args[1:], stdout)
	default:
		return fmt.Errorf("unknown docs subcommand %q (supported: markdown)", args[0])
	}
}

func docsMarkdownCommand(_ context.Context, args []string, _ io.Writer) error {
	fs := flag.NewFlagSet("docs markdown", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	out := fs.String("out", "", "")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if strings.TrimSpace(*out) == "" {
		return errors.New("usage: hasp docs markdown --out <path>")
	}
	if fs.NArg() != 0 {
		return errors.New("usage: hasp docs markdown --out <path>")
	}
	expandedOut, err := expandUserPath(strings.TrimSpace(*out))
	if err != nil {
		return fmt.Errorf("--out: %w", err)
	}
	*out = expandedOut
	body := renderDocsMarkdown()
	if err := os.WriteFile(*out, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", *out, err)
	}
	return nil
}

func renderDocsMarkdown() string {
	var b strings.Builder
	b.WriteString("# HASP CLI reference\n\n")
	fmt.Fprintf(&b, "Build: %s (%s)\n\n", runtime.VersionString(), runtime.CommitString())
	b.WriteString("Generated by `hasp docs markdown`. Every help topic is rendered\n")
	b.WriteString("verbatim inside a fenced code block so leading whitespace and\n")
	b.WriteString("table characters survive the markdown round-trip.\n\n")
	b.WriteString("## Root help\n\n")
	b.WriteString("```\n")
	b.WriteString(renderRootHelpText())
	b.WriteString("```\n\n")
	for _, spec := range helpTopicInventory {
		fmt.Fprintf(&b, "## hasp %s\n\n", spec.key)
		b.WriteString("```\n")
		b.WriteString(spec.text)
		if !strings.HasSuffix(spec.text, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("```\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}
