package app

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/gethasp/hasp/apps/server/internal/gitsafe"
	"github.com/gethasp/hasp/apps/server/internal/store"
)

const (
	projectExampleGeneratedMarker = "hasp-generated by hasp project examples"
	projectExampleSecretValue     = "__HASP_SECRET__"
	projectExamplePublicValue     = "__HASP_PUBLIC_CONFIG__"
	projectExampleFileValue       = "__HASP_FILE__"
)

type projectRequirementView struct {
	Ref              string         `json:"ref"`
	Kind             store.ItemKind `json:"kind"`
	Classification   string         `json:"classification"`
	Required         bool           `json:"required"`
	Present          bool           `json:"present"`
	Exposed          bool           `json:"exposed"`
	VaultAvailable   bool           `json:"vault_available"`
	Targets          []string       `json:"targets,omitempty"`
	SuggestedCommand string         `json:"suggested_command,omitempty"`
}

type projectTargetView struct {
	Name           string   `json:"name"`
	Refs           []string `json:"refs,omitempty"`
	CredentialSets []string `json:"credential_sets,omitempty"`
	HasCommand     bool     `json:"has_command"`
	HasEnv         bool     `json:"has_env"`
	HasFiles       bool     `json:"has_files"`
	HasXCConfig    bool     `json:"has_xcconfig"`
	HasExamples    bool     `json:"has_examples"`
	HasEnvSample   bool     `json:"has_env_example"`
	HasXCSample    bool     `json:"has_xcconfig_example"`
}

type projectExampleResult struct {
	Target  string `json:"target"`
	Missing bool   `json:"missing"`
	Stale   bool   `json:"stale"`
	Written bool   `json:"written"`
}

type projectDoctorDiagnostic struct {
	Code           string         `json:"code"`
	Severity       string         `json:"severity"`
	Target         string         `json:"target,omitempty"`
	Ref            string         `json:"ref,omitempty"`
	Kind           store.ItemKind `json:"kind,omitempty"`
	Classification string         `json:"classification,omitempty"`
	Present        bool           `json:"present,omitempty"`
	Exposed        bool           `json:"exposed,omitempty"`
	Ignored        bool           `json:"ignored,omitempty"`
	Stale          bool           `json:"stale,omitempty"`
}

type projectManifestWriteResult struct {
	ProjectRoot  string   `json:"project_root"`
	ManifestPath string   `json:"manifest_path"`
	Created      bool     `json:"created"`
	Updated      bool     `json:"updated"`
	Target       string   `json:"target,omitempty"`
	Refs         []string `json:"refs,omitempty"`
	Command      bool     `json:"command,omitempty"`
}

func projectManifestInitCommand(ctx context.Context, args []string, stdout io.Writer) error {
	fs := flag.NewFlagSet("project init", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	jsonOutput := fs.Bool("json", false, "")
	projectRoot := fs.String("project-root", ".", "")
	projectName := fs.String("name", "", "")
	description := fs.String("description", "", "")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return errors.New("usage: hasp project init --project-root <path> [--name <name>] [--description <text>] [--json]")
	}
	root, err := prepareManifestProjectRoot(*projectRoot)
	if err != nil {
		return err
	}
	manifestPath := filepath.Join(root, ".hasp.manifest.json")
	if _, err := appReadFileFn(manifestPath); err == nil {
		return newAppError(errCodeUserInput, "HASP project manifest already exists").
			withHint("use `hasp project target add <name> ...` or `hasp template add <name> ...` to add a value-free target")
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	name := strings.TrimSpace(*projectName)
	if name == "" {
		name = filepath.Base(root)
	}
	manifest := store.RepoManifest{
		Version: "v1",
		Project: store.ManifestProject{
			Name:        name,
			Description: strings.TrimSpace(*description),
		},
		References: []store.ManifestReference{},
	}
	if err := writeProjectManifest(root, manifest); err != nil {
		return err
	}
	result := projectManifestWriteResult{ProjectRoot: root, ManifestPath: manifestPath, Created: true}
	return renderJSONOrHuman(ctx, stdout, *jsonOutput, result, func(w io.Writer) error {
		return renderProjectManifestWriteResult(w, "Project manifest created", "Created a value-free HASP manifest.", result)
	})
}

func projectTargetCommand(ctx context.Context, args []string, stdout io.Writer) error {
	if len(args) == 0 || isHelpArg(args[0]) {
		return errors.New("usage: hasp project target add|review <name> [flags]")
	}
	switch args[0] {
	case "add":
		return projectTargetAddCommand(ctx, args[1:], stdout)
	case "review":
		return projectTargetReviewCommand(ctx, args[1:], stdout)
	default:
		return fmt.Errorf("unknown project target subcommand %q", args[0])
	}
}

func projectTargetAddCommand(ctx context.Context, args []string, stdout io.Writer) error {
	if len(args) == 0 || strings.HasPrefix(args[0], "-") {
		return errors.New("usage: hasp project target add <name> --env NAME=@REF [--file NAME=@REF] [--root <path>] [-- <command>]")
	}
	targetName := strings.TrimSpace(args[0])
	fs := flag.NewFlagSet("project target add", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	jsonOutput := fs.Bool("json", false, "")
	projectRoot := fs.String("project-root", ".", "")
	targetRoot := fs.String("root", ".", "")
	description := fs.String("description", "", "")
	envExample := fs.String("env-example", "", "")
	var envRefs mappingFlag
	var fileRefs mappingFlag
	fs.Var(&envRefs, "env", "NAME=@REF")
	fs.Var(&fileRefs, "file", "NAME=@REF")
	if err := fs.Parse(args[1:]); err != nil {
		return err
	}
	command := slices.Clone(fs.Args())
	if len(envRefs) == 0 && len(fileRefs) == 0 {
		return errors.New("project target add requires at least one --env or --file mapping")
	}
	root, err := prepareManifestProjectRoot(*projectRoot)
	if err != nil {
		return err
	}
	manifest, created, err := loadOrCreateProjectManifest(root)
	if err != nil {
		return err
	}
	if _, ok := manifest.Target(targetName); ok {
		return newAppError(errCodeUserInput, fmt.Sprintf("manifest target %q already exists", targetName)).
			withHint("choose a new target name, or edit .hasp.manifest.json intentionally")
	}
	existingAliases := manifestAliasMap(manifest)
	delivery := make([]store.ManifestDelivery, 0, len(envRefs)+len(fileRefs))
	refs := make([]string, 0, len(envRefs)+len(fileRefs))
	for name, ref := range envRefs {
		if err := ensureManifestRequirementForNamedRef(&manifest, &existingAliases, ref, store.ItemKindKV); err != nil {
			return err
		}
		delivery = append(delivery, store.ManifestDelivery{As: store.ManifestDeliveryEnv, Name: name, Ref: ref})
		refs = append(refs, ref)
	}
	for name, ref := range fileRefs {
		if err := ensureManifestRequirementForNamedRef(&manifest, &existingAliases, ref, store.ItemKindFile); err != nil {
			return err
		}
		delivery = append(delivery, store.ManifestDelivery{As: store.ManifestDeliveryFile, Name: name, Ref: ref})
		refs = append(refs, ref)
	}
	slices.SortFunc(delivery, func(a, b store.ManifestDelivery) int {
		if a.As != b.As {
			return strings.Compare(a.As, b.As)
		}
		return strings.Compare(a.Name, b.Name)
	})
	examples := []store.ManifestExample{}
	if strings.TrimSpace(*envExample) != "" {
		examples = append(examples, store.ManifestExample{Format: store.ManifestExampleEnv, Path: strings.TrimSpace(*envExample)})
	}
	manifest.Targets = append(manifest.Targets, store.ManifestTarget{
		Name:        targetName,
		Description: strings.TrimSpace(*description),
		Root:        strings.TrimSpace(*targetRoot),
		Command:     command,
		Delivery:    delivery,
		Examples:    examples,
	})
	if err := writeProjectManifest(root, manifest); err != nil {
		return err
	}
	slices.Sort(refs)
	refs = slices.Compact(refs)
	result := projectManifestWriteResult{
		ProjectRoot:  root,
		ManifestPath: filepath.Join(root, ".hasp.manifest.json"),
		Created:      created,
		Updated:      !created,
		Target:       targetName,
		Refs:         refs,
		Command:      len(command) > 0,
	}
	return renderJSONOrHuman(ctx, stdout, *jsonOutput, result, func(w io.Writer) error {
		return renderProjectManifestWriteResult(w, "Project target added", "Added a value-free HASP manifest target.", result)
	})
}

func projectTargetReviewCommand(ctx context.Context, args []string, stdout io.Writer) error {
	if len(args) == 0 || strings.HasPrefix(args[0], "-") {
		return errors.New("usage: hasp project target review <name> --project-root <path> [--json]")
	}
	targetName := strings.TrimSpace(args[0])
	fs := flag.NewFlagSet("project target review", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	jsonOutput := fs.Bool("json", false, "")
	projectRoot := fs.String("project-root", ".", "")
	if err := fs.Parse(args[1:]); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return errors.New("usage: hasp project target review <name> --project-root <path> [--json]")
	}
	root, err := prepareManifestProjectRoot(*projectRoot)
	if err != nil {
		return err
	}
	expansion, err := store.ExpandManifestTarget(root, targetName)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return newAppError(errCodeNotFound, "no HASP project manifest found").
				withHint("run `hasp project init --project-root .`, then `hasp project target add <name> --env NAME=@REF -- <command>`")
		}
		return err
	}
	handle, err := openVaultHandleFn(ctx)
	if err != nil {
		return err
	}
	if err := recordManifestReviewFn(handle, root, expansion); err != nil {
		return err
	}
	result := projectManifestWriteResult{
		ProjectRoot:  root,
		ManifestPath: filepath.Join(root, ".hasp.manifest.json"),
		Target:       expansion.TargetName,
		Refs:         expansion.Refs,
		Command:      len(expansion.Command) > 0,
	}
	return renderJSONOrHuman(ctx, stdout, *jsonOutput, result, func(w io.Writer) error {
		return renderProjectManifestWriteResult(w, "Project target reviewed", "Recorded the value-free target signature for local drift checks.", result)
	})
}

func projectRequirementsCommand(ctx context.Context, args []string, stdout io.Writer) error {
	fs := flag.NewFlagSet("project requirements", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	jsonOutput := fs.Bool("json", false, "")
	projectRoot := fs.String("project-root", ".", "")
	targetName := fs.String("target", "", "")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return errors.New("usage: hasp project requirements --project-root <path> [--target <name>] [--json]")
	}

	root, manifest, err := loadProjectManifest(*projectRoot)
	if err != nil {
		return err
	}

	reqs, err := projectRequirementViews(ctx, root, manifest, strings.TrimSpace(*targetName))
	if err != nil {
		return err
	}
	payload := map[string]any{"requirements": reqs}
	return renderJSONOrHuman(ctx, stdout, *jsonOutput, payload, func(w io.Writer) error {
		return renderProjectRequirements(w, root, strings.TrimSpace(*targetName), reqs)
	})
}

func projectTargetsCommand(ctx context.Context, args []string, stdout io.Writer) error {
	fs := flag.NewFlagSet("project targets", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	jsonOutput := fs.Bool("json", false, "")
	projectRoot := fs.String("project-root", ".", "")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return errors.New("usage: hasp project targets --project-root <path> [--json]")
	}

	root, manifest, err := loadProjectManifest(*projectRoot)
	if err != nil {
		return err
	}

	targets := projectTargetViews(manifest)
	payload := map[string]any{"targets": targets}
	return renderJSONOrHuman(ctx, stdout, *jsonOutput, payload, func(w io.Writer) error {
		return renderProjectTargets(w, root, targets)
	})
}

func projectExamplesCommand(ctx context.Context, args []string, stdout io.Writer) error {
	fs := flag.NewFlagSet("project examples", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	jsonOutput := fs.Bool("json", false, "")
	projectRoot := fs.String("project-root", ".", "")
	targetName := fs.String("target", "", "")
	check := fs.Bool("check", false, "")
	write := fs.Bool("write", false, "")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return errors.New("usage: hasp project examples --project-root <path> [--target <name>] --check|--write")
	}
	if *check == *write {
		return errors.New("choose exactly one of --check or --write")
	}

	root, manifest, err := loadProjectManifest(*projectRoot)
	if err != nil {
		return err
	}

	targets, err := selectedManifestTargets(manifest, strings.TrimSpace(*targetName))
	if err != nil {
		return err
	}
	results, err := projectExampleActions(root, manifest, targets, *write)
	if err != nil {
		return err
	}
	payload := map[string]any{"results": results}
	return renderJSONOrHuman(ctx, stdout, *jsonOutput, payload, func(w io.Writer) error {
		return renderProjectExamples(w, root, results, *write)
	})
}

func projectManifestDoctorCommand(ctx context.Context, args []string, stdout io.Writer) error {
	fs := flag.NewFlagSet("project doctor", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	jsonOutput := fs.Bool("json", false, "")
	projectRoot := fs.String("project-root", ".", "")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return errors.New("usage: hasp project doctor --project-root <path> [--json]")
	}

	root, manifest, err := loadProjectManifest(*projectRoot)
	if err != nil {
		return err
	}
	diagnostics := buildProjectDoctorDiagnostics(ctx, root, manifest)
	payload := map[string]any{"diagnostics": diagnostics}
	return renderJSONOrHuman(ctx, stdout, *jsonOutput, payload, func(w io.Writer) error {
		return renderProjectDoctor(w, root, diagnostics)
	})
}

func loadProjectManifest(projectRoot string) (string, store.RepoManifest, error) {
	root, err := expandUserPath(strings.TrimSpace(projectRoot))
	if err != nil {
		return "", store.RepoManifest{}, fmt.Errorf("--project-root: %w", err)
	}
	manifest, err := store.LoadRepoManifest(root)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return "", store.RepoManifest{}, newAppError(errCodeNotFound, "no HASP project manifest found").
				withHint("run `hasp project init --project-root .`, then `hasp project target add <name> --env NAME=@REF -- <command>`")
		}
		return "", store.RepoManifest{}, err
	}
	return root, manifest, nil
}

func prepareManifestProjectRoot(projectRoot string) (string, error) {
	root, err := expandUserPath(strings.TrimSpace(projectRoot))
	if err != nil {
		return "", fmt.Errorf("--project-root: %w", err)
	}
	info, err := os.Stat(root)
	if err != nil {
		return "", err
	}
	if !info.IsDir() {
		return "", fmt.Errorf("project root %q is not a directory", root)
	}
	return root, nil
}

func loadOrCreateProjectManifest(root string) (store.RepoManifest, bool, error) {
	manifest, err := store.LoadRepoManifest(root)
	if err == nil {
		return manifest, false, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return store.RepoManifest{}, false, err
	}
	return store.RepoManifest{
		Version:    "v1",
		Project:    store.ManifestProject{Name: filepath.Base(root)},
		References: []store.ManifestReference{},
	}, true, nil
}

func writeProjectManifest(root string, manifest store.RepoManifest) error {
	data, _ := json.MarshalIndent(manifest, "", "  ")
	data = append(data, '\n')
	if _, err := store.DecodeRepoManifest(root, data); err != nil {
		return err
	}
	return appWriteFileFn(filepath.Join(root, ".hasp.manifest.json"), data, 0o600)
}

func manifestAliasMap(manifest store.RepoManifest) map[string]string {
	out := map[string]string{}
	for _, ref := range manifest.References {
		alias := strings.TrimSpace(ref.Alias)
		item := strings.TrimSpace(ref.Item)
		if alias != "" && item != "" {
			out[alias] = item
		}
	}
	return out
}

func ensureManifestRequirementForNamedRef(manifest *store.RepoManifest, existingAliases *map[string]string, ref string, kind store.ItemKind) error {
	ref = strings.TrimSpace(ref)
	itemName, ok := manifestItemNameFromNamedRef(ref)
	if !ok {
		return fmt.Errorf("manifest authoring refs must be named refs like @OPENAI_API_KEY, got %q", ref)
	}
	for _, req := range manifest.Requirements {
		if strings.TrimSpace(req.Ref) == ref {
			if req.Kind != kind {
				return fmt.Errorf("manifest requirement %q is already declared as %s", ref, req.Kind)
			}
			return nil
		}
	}
	declared := false
	for _, declaredRef := range manifest.References {
		if strings.TrimSpace(declaredRef.Item) == itemName {
			declared = true
			break
		}
	}
	if !declared {
		alias := store.GenerateNeutralAlias(kind, *existingAliases)
		(*existingAliases)[alias] = itemName
		manifest.References = append(manifest.References, store.ManifestReference{Alias: alias, Item: itemName})
	}
	manifest.Requirements = append(manifest.Requirements, store.ManifestRequirement{
		Ref:            ref,
		Kind:           kind,
		Required:       true,
		Classification: store.ManifestClassificationSecret,
	})
	return nil
}

func manifestItemNameFromNamedRef(ref string) (string, bool) {
	ref = strings.TrimSpace(ref)
	if !strings.HasPrefix(ref, "@") {
		return "", false
	}
	name := strings.TrimSpace(strings.TrimPrefix(ref, "@"))
	if name == "" || strings.ContainsAny(name, " \t\r\n") {
		return "", false
	}
	return name, true
}

func selectedManifestTargets(manifest store.RepoManifest, targetName string) ([]store.ManifestTarget, error) {
	if targetName == "" {
		return slices.Clone(manifest.Targets), nil
	}
	target, ok := manifest.Target(targetName)
	if !ok {
		return nil, fmt.Errorf("unknown manifest target %q", targetName)
	}
	return []store.ManifestTarget{target}, nil
}

func projectRequirementViews(ctx context.Context, projectRoot string, manifest store.RepoManifest, targetName string) ([]projectRequirementView, error) {
	targets, err := selectedManifestTargets(manifest, targetName)
	if err != nil {
		return nil, err
	}
	filter := map[string][]string{}
	for _, target := range targets {
		seen := map[string]struct{}{}
		for _, delivery := range target.Delivery {
			ref, ok := manifest.DeliveryRef(delivery)
			if !ok {
				continue
			}
			if _, ok := seen[ref]; ok {
				continue
			}
			seen[ref] = struct{}{}
			filter[ref] = append(filter[ref], target.Name)
		}
	}
	var handle *store.Handle
	if opened, err := openVaultHandleFn(ctx); err == nil {
		handle = opened
	}
	views := make([]projectRequirementView, 0, len(manifest.Requirements))
	for _, req := range manifest.Requirements {
		targets := filter[req.Ref]
		if targetName != "" && len(targets) == 0 {
			continue
		}
		itemName, hasItemName := manifest.ItemNameForRef(req.Ref)
		present, exposed := projectRequirementState(ctx, handle, projectRoot, req.Ref, itemName, hasItemName)
		views = append(views, projectRequirementView{
			Ref:              req.Ref,
			Kind:             req.Kind,
			Classification:   req.Classification,
			Required:         req.Required,
			Present:          present,
			Exposed:          exposed,
			VaultAvailable:   handle != nil,
			Targets:          slices.Clone(targets),
			SuggestedCommand: projectRequirementSuggestion(req, itemName, hasItemName, present),
		})
	}
	return views, nil
}

func projectRequirementState(ctx context.Context, handle *store.Handle, projectRoot string, ref string, itemName string, hasItemName bool) (bool, bool) {
	if handle == nil {
		return false, false
	}
	present := false
	if hasItemName {
		_, err := handle.GetItem(itemName)
		present = err == nil
	}
	_, err := handle.ResolveReference(ctx, projectRoot, ref)
	return present, err == nil
}

func projectRequirementSuggestion(req store.ManifestRequirement, itemName string, hasItemName bool, present bool) string {
	if present || !hasItemName {
		return ""
	}
	kindFlag := ""
	if req.Kind == store.ItemKindFile {
		kindFlag = " --kind file"
	}
	return "hasp secret add" + kindFlag + " " + itemName
}

func projectTargetViews(manifest store.RepoManifest) []projectTargetView {
	views := make([]projectTargetView, 0, len(manifest.Targets))
	for _, target := range manifest.Targets {
		view := projectTargetView{
			Name:        target.Name,
			HasCommand:  len(target.Command) > 0,
			HasExamples: len(target.Examples) > 0,
		}
		refSeen := map[string]struct{}{}
		setSeen := map[string]struct{}{}
		for _, delivery := range target.Delivery {
			switch strings.TrimSpace(delivery.As) {
			case store.ManifestDeliveryEnv:
				view.HasEnv = true
			case store.ManifestDeliveryFile:
				view.HasFiles = true
			case store.ManifestDeliveryXCConfig:
				view.HasXCConfig = true
			}
			if set, ok := manifest.DeliveryCredentialSet(delivery); ok {
				if _, ok := setSeen[set.Name]; !ok {
					setSeen[set.Name] = struct{}{}
					view.CredentialSets = append(view.CredentialSets, set.Name)
				}
			}
			if ref, ok := manifest.DeliveryRef(delivery); ok {
				if _, ok := refSeen[ref]; ok {
					continue
				}
				refSeen[ref] = struct{}{}
				view.Refs = append(view.Refs, ref)
			}
		}
		for _, example := range target.Examples {
			switch strings.TrimSpace(example.Format) {
			case store.ManifestExampleEnv:
				view.HasEnvSample = true
			case store.ManifestExampleXCConfig:
				view.HasXCSample = true
			}
		}
		slices.Sort(view.Refs)
		slices.Sort(view.CredentialSets)
		views = append(views, view)
	}
	return views
}

func projectExampleActions(projectRoot string, manifest store.RepoManifest, targets []store.ManifestTarget, write bool) ([]projectExampleResult, error) {
	results := make([]projectExampleResult, 0)
	for _, target := range targets {
		for _, example := range target.Examples {
			desired, err := renderProjectExample(manifest, target, example)
			if err != nil {
				return nil, err
			}
			path := filepath.Join(projectRoot, filepath.Clean(example.Path))
			existing, err := appReadFileFn(path)
			result := projectExampleResult{Target: target.Name}
			switch {
			case errors.Is(err, os.ErrNotExist):
				result.Missing = true
				if write {
					if err := appMkdirAllFn(filepath.Dir(path), 0o755); err != nil {
						return nil, err
					}
					if err := appWriteFileFn(path, desired, 0o600); err != nil {
						return nil, err
					}
					result.Missing = false
					result.Written = true
				}
			case err != nil:
				return nil, err
			case !bytes.Equal(existing, desired):
				result.Stale = true
				if write {
					if !bytes.Contains(existing, []byte(projectExampleGeneratedMarker)) {
						return nil, fmt.Errorf("refusing to overwrite unmanaged example file %q", path)
					}
					if err := appWriteFileFn(path, desired, 0o600); err != nil {
						return nil, err
					}
					result.Stale = false
					result.Written = true
				}
			}
			results = append(results, result)
		}
	}
	return results, nil
}

func renderProjectExample(manifest store.RepoManifest, target store.ManifestTarget, example store.ManifestExample) ([]byte, error) {
	lines := []string{}
	switch strings.TrimSpace(example.Format) {
	case store.ManifestExampleEnv:
		lines = append(lines,
			"# "+projectExampleGeneratedMarker,
			"# placeholder values only",
		)
		for _, delivery := range target.Delivery {
			if strings.TrimSpace(delivery.As) != store.ManifestDeliveryEnv {
				continue
			}
			ref, ok := manifest.DeliveryRef(delivery)
			if !ok {
				return nil, fmt.Errorf("delivery %q in target %q references an unresolved credential role", delivery.Name, target.Name)
			}
			req, ok := manifest.Requirement(ref)
			if !ok {
				return nil, fmt.Errorf("delivery %q in target %q references unknown requirement %q", delivery.Name, target.Name, ref)
			}
			lines = append(lines, strings.TrimSpace(delivery.Name)+"="+strconv.Quote(projectExamplePlaceholder(req)))
		}
	case store.ManifestExampleXCConfig:
		lines = append(lines,
			"// "+projectExampleGeneratedMarker,
			"// placeholder values only",
		)
		for _, delivery := range target.Delivery {
			if strings.TrimSpace(delivery.As) != store.ManifestDeliveryXCConfig {
				continue
			}
			ref, ok := manifest.DeliveryRef(delivery)
			if !ok {
				return nil, fmt.Errorf("delivery %q in target %q references an unresolved credential role", delivery.Name, target.Name)
			}
			req, ok := manifest.Requirement(ref)
			if !ok {
				return nil, fmt.Errorf("delivery %q in target %q references unknown requirement %q", delivery.Name, target.Name, ref)
			}
			lines = append(lines, strings.TrimSpace(delivery.Name)+" = "+projectExamplePlaceholder(req))
		}
	default:
		return nil, fmt.Errorf("unsupported manifest example format %q", example.Format)
	}
	return []byte(strings.Join(lines, "\n") + "\n"), nil
}

func projectExamplePlaceholder(req store.ManifestRequirement) string {
	if req.Kind == store.ItemKindFile {
		return projectExampleFileValue
	}
	if strings.TrimSpace(req.Classification) == store.ManifestClassificationPublicConfig {
		return projectExamplePublicValue
	}
	return projectExampleSecretValue
}

func buildProjectDoctorDiagnostics(ctx context.Context, projectRoot string, manifest store.RepoManifest) []projectDoctorDiagnostic {
	diagnostics := make([]projectDoctorDiagnostic, 0, len(manifest.Requirements)+len(manifest.Targets))
	exposedByRef := map[string]bool{}
	for _, target := range manifest.Targets {
		for _, delivery := range target.Delivery {
			if ref, ok := manifest.DeliveryRef(delivery); ok {
				exposedByRef[ref] = true
			}
		}
	}

	var handle *store.Handle
	if opened, err := openVaultHandleFn(ctx); err == nil {
		handle = opened
	} else {
		diagnostics = append(diagnostics, projectDoctorDiagnostic{
			Code:     "vault_unavailable",
			Severity: "warning",
			Ignored:  true,
		})
	}

	for _, req := range manifest.Requirements {
		itemName, hasItemName := manifest.ItemNameForRef(req.Ref)
		present, exposed := projectRequirementState(ctx, handle, projectRoot, req.Ref, itemName, hasItemName)
		code := "requirement_ok"
		severity := "info"
		switch {
		case !present:
			code = "requirement_missing"
			severity = "warning"
		case !exposed:
			code = "requirement_unexposed"
			severity = "warning"
		case !exposedByRef[req.Ref]:
			code = "requirement_unused"
			severity = "warning"
		}
		if present && handle != nil && hasItemName {
			if item, err := handle.GetItem(itemName); err == nil && item.Kind != req.Kind {
				code = "requirement_kind_mismatch"
				severity = "error"
			}
		}
		diagnostics = append(diagnostics, projectDoctorDiagnostic{
			Code:           code,
			Severity:       severity,
			Ref:            req.Ref,
			Kind:           req.Kind,
			Classification: req.Classification,
			Present:        present,
			Exposed:        exposed,
		})
	}

	for _, target := range manifest.Targets {
		if len(target.Command) > 0 && !projectTargetCommandAvailable(projectRoot, target) {
			diagnostics = append(diagnostics, projectDoctorDiagnostic{
				Code:     "target_command_unavailable",
				Severity: "warning",
				Target:   target.Name,
			})
		}
		for _, delivery := range target.Delivery {
			ref, ok := manifest.DeliveryRef(delivery)
			if !ok {
				continue
			}
			req, ok := manifest.Requirement(ref)
			if !ok {
				continue
			}
			if strings.TrimSpace(delivery.As) == store.ManifestDeliveryXCConfig && strings.TrimSpace(req.Classification) == store.ManifestClassificationSecret {
				diagnostics = append(diagnostics, projectDoctorDiagnostic{
					Code:           "secret_workspace_delivery",
					Severity:       "warning",
					Target:         target.Name,
					Ref:            ref,
					Kind:           req.Kind,
					Classification: req.Classification,
				})
			}
			if strings.TrimSpace(delivery.Output) != "" && !projectGeneratedOutputIgnored(ctx, projectRoot, delivery.Output) {
				diagnostics = append(diagnostics, projectDoctorDiagnostic{
					Code:     "target_output_unignored",
					Severity: "warning",
					Target:   target.Name,
					Ignored:  false,
				})
			}
		}
		if handle != nil {
			if expansion, err := store.ExpandManifestTarget(projectRoot, target.Name); err == nil {
				if drift, err := handle.ManifestTargetDrift(projectRoot, expansion); err == nil && drift.Changed {
					diagnostics = append(diagnostics, projectDoctorDiagnostic{
						Code:     "target_drift",
						Severity: "warning",
						Target:   target.Name,
						Stale:    true,
					})
				}
			}
		}
		for _, example := range target.Examples {
			desired, err := renderProjectExample(manifest, target, example)
			if err != nil {
				diagnostics = append(diagnostics, projectDoctorDiagnostic{
					Code:     "example_invalid",
					Severity: "error",
					Target:   target.Name,
					Stale:    true,
				})
				continue
			}
			path := filepath.Join(projectRoot, filepath.Clean(example.Path))
			existing, readErr := appReadFileFn(path)
			diag := projectDoctorDiagnostic{
				Code:     "example_ok",
				Severity: "info",
				Target:   target.Name,
			}
			switch {
			case errors.Is(readErr, os.ErrNotExist):
				diag.Code = "example_missing"
				diag.Severity = "warning"
				diag.Present = false
				diag.Stale = true
			case readErr != nil:
				diag.Code = "example_unreadable"
				diag.Severity = "warning"
				diag.Ignored = true
			case !bytes.Equal(existing, desired):
				diag.Code = "example_stale"
				diag.Severity = "warning"
				diag.Present = true
				diag.Stale = true
			default:
				diag.Present = true
			}
			diagnostics = append(diagnostics, diag)
		}
	}

	return diagnostics
}

func projectTargetCommandAvailable(projectRoot string, target store.ManifestTarget) bool {
	command := strings.TrimSpace(target.Command[0])
	if filepath.IsAbs(command) || strings.ContainsRune(command, os.PathSeparator) {
		commandPath := command
		if !filepath.IsAbs(commandPath) {
			commandPath = filepath.Join(projectRoot, filepath.Clean(target.Root), commandPath)
		}
		info, err := os.Stat(commandPath)
		return err == nil && !info.IsDir() && info.Mode()&0o111 != 0
	}
	_, err := setupLookPathFn(command)
	return err == nil
}

func projectGeneratedOutputIgnored(ctx context.Context, projectRoot string, output string) bool {
	outputPath := strings.TrimSpace(output)
	if !filepath.IsAbs(outputPath) {
		outputPath = filepath.Join(projectRoot, filepath.Clean(outputPath))
	}
	rel, err := filepath.Rel(projectRoot, outputPath)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(os.PathSeparator)) || filepath.IsAbs(rel) {
		return false
	}
	cmd := gitsafe.BuildCommand(ctx, projectRoot, "check-ignore", "-q", "--", filepath.ToSlash(rel))
	return cmd.Run() == nil
}

func renderProjectRequirements(w io.Writer, projectRoot string, targetName string, reqs []projectRequirementView) error {
	lead := fmt.Sprintf("Loaded %d %s from the repo manifest.", len(reqs), cliPlural(len(reqs), "requirement", "requirements"))
	if err := cliWriteStage(w, "Project requirements", lead); err != nil {
		return err
	}
	if err := cliWriteKeyValues(w, "Project",
		cliPair("Project root", cliDisplayPath(projectRoot)),
		cliPair("Target", targetName),
	); err != nil {
		return err
	}
	if err := cliSection(w, "Requirements"); err != nil {
		return err
	}
	if len(reqs) == 0 {
		_, err := fmt.Fprintln(w, "  none")
		return err
	}
	for _, req := range reqs {
		details := []string{
			setupSummaryValue(w, string(req.Kind)),
			setupSummaryValue(w, req.Classification),
			cliMuted(w, "(required "+setupYesNo(req.Required)+")"),
		}
		if len(req.Targets) > 0 {
			details = append(details, cliMuted(w, "("+strings.Join(req.Targets, ", ")+")"))
		}
		if req.VaultAvailable {
			details = append(details, cliMuted(w, "(present "+setupYesNo(req.Present)+")"))
			details = append(details, cliMuted(w, "(exposed "+setupYesNo(req.Exposed)+")"))
		} else {
			details = append(details, cliMuted(w, "(vault unavailable)"))
		}
		if _, err := fmt.Fprintln(w, cliBullet(w, fmt.Sprintf("%-22s", req.Ref), details...)); err != nil {
			return err
		}
		if req.SuggestedCommand != "" {
			if _, err := fmt.Fprintln(w, "    "+req.SuggestedCommand); err != nil {
				return err
			}
		}
	}
	return nil
}

func renderProjectTargets(w io.Writer, projectRoot string, targets []projectTargetView) error {
	lead := fmt.Sprintf("Loaded %d %s from the repo manifest.", len(targets), cliPlural(len(targets), "target", "targets"))
	if err := cliWriteStage(w, "Project targets", lead); err != nil {
		return err
	}
	if err := cliWriteKeyValues(w, "Project",
		cliPair("Project root", cliDisplayPath(projectRoot)),
	); err != nil {
		return err
	}
	if err := cliSection(w, "Targets"); err != nil {
		return err
	}
	if len(targets) == 0 {
		_, err := fmt.Fprintln(w, "  none")
		return err
	}
	for _, target := range targets {
		details := []string{
			cliMuted(w, fmt.Sprintf("(refs %d)", len(target.Refs))),
			cliMuted(w, fmt.Sprintf("(command %s)", setupYesNo(target.HasCommand))),
			cliMuted(w, fmt.Sprintf("(examples %s)", setupYesNo(target.HasExamples))),
		}
		if _, err := fmt.Fprintln(w, cliBullet(w, fmt.Sprintf("%-22s", target.Name), details...)); err != nil {
			return err
		}
	}
	return nil
}

func renderProjectExamples(w io.Writer, projectRoot string, results []projectExampleResult, wrote bool) error {
	title := "Project examples"
	lead := "Checked repo-managed example files without writing."
	if wrote {
		lead = "Wrote repo-managed example files."
	}
	if err := cliWriteStage(w, title, lead); err != nil {
		return err
	}
	if err := cliWriteKeyValues(w, "Project",
		cliPair("Project root", cliDisplayPath(projectRoot)),
		cliPair("Write mode", setupYesNo(wrote)),
	); err != nil {
		return err
	}
	if err := cliSection(w, "Targets"); err != nil {
		return err
	}
	if len(results) == 0 {
		_, err := fmt.Fprintln(w, "  none")
		return err
	}
	for _, result := range results {
		outcome := "ok"
		switch {
		case result.Written:
			outcome = "written"
		case result.Missing:
			outcome = "missing"
		case result.Stale:
			outcome = "stale"
		}
		if _, err := fmt.Fprintln(w, cliBullet(w, fmt.Sprintf("%-22s", result.Target), cliOutcome(w, outcome))); err != nil {
			return err
		}
	}
	return nil
}

func renderProjectDoctor(w io.Writer, projectRoot string, diagnostics []projectDoctorDiagnostic) error {
	lead := fmt.Sprintf("Collected %d safe project-target diagnostics.", len(diagnostics))
	if err := cliWriteStage(w, "Project doctor", lead); err != nil {
		return err
	}
	if err := cliWriteKeyValues(w, "Project",
		cliPair("Project root", cliDisplayPath(projectRoot)),
	); err != nil {
		return err
	}
	if err := cliSection(w, "Diagnostics"); err != nil {
		return err
	}
	if len(diagnostics) == 0 {
		_, err := fmt.Fprintln(w, "  none")
		return err
	}
	for _, diag := range diagnostics {
		label := diag.Code
		if diag.Ref != "" {
			label = diag.Ref
		} else if diag.Target != "" {
			label = diag.Target
		}
		details := []string{
			setupSummaryValue(w, diag.Code),
			setupSummaryValue(w, diag.Severity),
		}
		if diag.Kind != "" {
			details = append(details, setupSummaryValue(w, string(diag.Kind)))
		}
		if diag.Classification != "" {
			details = append(details, setupSummaryValue(w, diag.Classification))
		}
		if diag.Present {
			details = append(details, cliMuted(w, "(present true)"))
		}
		if diag.Exposed {
			details = append(details, cliMuted(w, "(exposed true)"))
		}
		if diag.Stale {
			details = append(details, cliMuted(w, "(stale true)"))
		}
		if diag.Ignored {
			details = append(details, cliMuted(w, "(ignored true)"))
		}
		if _, err := fmt.Fprintln(w, cliBullet(w, fmt.Sprintf("%-22s", label), details...)); err != nil {
			return err
		}
	}
	return nil
}

func renderProjectManifestWriteResult(w io.Writer, title string, lead string, result projectManifestWriteResult) error {
	if err := cliWriteStage(w, title, lead); err != nil {
		return err
	}
	if err := cliWriteKeyValues(w, "Manifest",
		cliPair("Project root", cliDisplayPath(result.ProjectRoot)),
		cliPair("Manifest", cliDisplayPath(result.ManifestPath)),
		cliPair("Created", setupYesNo(result.Created)),
		cliPair("Updated", setupYesNo(result.Updated)),
	); err != nil {
		return err
	}
	if strings.TrimSpace(result.Target) != "" {
		if err := cliWriteKeyValues(w, "Target",
			cliPair("Name", result.Target),
			cliPair("Refs", strings.Join(result.Refs, ", ")),
			cliPair("Command", setupYesNo(result.Command)),
		); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintln(w, "Next steps"); err != nil {
		return err
	}
	if result.Target == "" {
		_, err := fmt.Fprintln(w, "  hasp project target add <name> --env NAME=@REF -- <command>")
		return err
	}
	if _, err := fmt.Fprintf(w, "  hasp project doctor --project-root %s\n", strconv.Quote(result.ProjectRoot)); err != nil {
		return err
	}
	_, err := fmt.Fprintf(w, "  hasp run --project-root %s --target %s --explain --dry-run\n", strconv.Quote(result.ProjectRoot), strconv.Quote(result.Target))
	return err
}
