#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TARGETS_PATH = REPO_ROOT / "scripts" / "release-targets.json"


def load_targets(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8") as handle:
        raw_targets = json.load(handle)
    targets: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for target in raw_targets:
        goos = str(target.get("goos", "")).strip()
        goarch = str(target.get("goarch", "")).strip()
        runner = str(target.get("runner", "")).strip()
        if not goos or not goarch or not runner:
            raise SystemExit(f"invalid release target entry: {target!r}")
        key = (goos, goarch)
        if key in seen:
            raise SystemExit(f"duplicate release target: {goos}/{goarch}")
        seen.add(key)
        targets.append({"goos": goos, "goarch": goarch, "runner": runner})
    if not targets:
        raise SystemExit("release target list is empty")
    return targets


def worker_js(targets: list[dict[str, str]]) -> str:
    entries = ",\n".join(f'  ["{target["goos"]}", "{target["goarch"]}"]' for target in targets)
    return f"""// Generated by scripts/release_targets.py. Do not edit by hand.
export const RELEASE_TARGETS = Object.freeze([
{entries},
]);
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "mode",
        choices=("shell", "github-matrix", "github-output", "has-target", "worker-js"),
    )
    parser.add_argument("target", nargs="?", help="Target for has-target mode, in goos/goarch form")
    parser.add_argument("--targets", default=str(DEFAULT_TARGETS_PATH))
    args = parser.parse_args()

    targets = load_targets(Path(args.targets))
    if args.mode == "shell":
        for target in targets:
            print(f'{target["goos"]} {target["goarch"]} {target["runner"]}')
        return 0
    if args.mode == "github-matrix":
        print(json.dumps({"include": targets}, separators=(",", ":")))
        return 0
    if args.mode == "github-output":
        print(f'matrix={json.dumps({"include": targets}, separators=(",", ":"))}')
        return 0
    if args.mode == "worker-js":
        print(worker_js(targets), end="")
        return 0
    if args.mode == "has-target":
        wanted = args.target or ""
        if "/" not in wanted:
            return 1
        goos, goarch = wanted.split("/", 1)
        return 0 if any(target["goos"] == goos and target["goarch"] == goarch for target in targets) else 1
    raise AssertionError(args.mode)


if __name__ == "__main__":
    raise SystemExit(main())
