package reposcan

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/gethasp/hasp/apps/server/internal/store"
)

func TestStagedBatchMatchesLegacyAndReadsFreshIndex(t *testing.T) {
	for _, format := range []string{"sha1", "sha256"} {
		t.Run(format, func(t *testing.T) {
			root := newOutgoingRepo(t, format)
			outgoingCommit(t, root, "old.txt", "safe", "base")
			outgoingGit(t, root, "mv", "old.txt", "renamed.txt")
			paths := []string{" leading\nfile ", "renamed.txt", "second.txt"}
			for _, path := range paths {
				if err := os.WriteFile(filepath.Join(root, path), outgoingTestItems[0].Value, 0o600); err != nil {
					t.Fatal(err)
				}
			}
			if err := os.Symlink(string(outgoingTestItems[0].Value), filepath.Join(root, "link")); err != nil {
				t.Fatal(err)
			}
			outgoingGit(t, root, "add", ".")
			legacy, err := ScanStaged(context.Background(), root, outgoingTestItems, 0, DefaultDeps())
			if err != nil {
				t.Fatal(err)
			}
			git, err := exec.LookPath("git")
			if err != nil {
				t.Fatal(err)
			}
			shim := t.TempDir()
			calls := filepath.Join(shim, "calls")
			// These temporary paths are generated by testing and contain no shell
			// metacharacters. Record invocations, without recording their argv.
			if err := os.WriteFile(filepath.Join(shim, "git"), []byte("#!/bin/sh\nprintf x >> '"+calls+"'\nexec '"+git+"' \"$@\"\n"), 0o700); err != nil {
				t.Fatal(err)
			}
			t.Setenv("PATH", shim+string(os.PathListSeparator)+os.Getenv("PATH"))
			got, err := ScanStaged(context.Background(), root, outgoingTestItems, 0, Deps{})
			if err != nil || !got.Complete || !reflect.DeepEqual(got.Matches, legacy.Matches) {
				t.Fatalf("batch changed coverage: %+v legacy=%+v err=%v", got, legacy, err)
			}
			invocations, err := os.ReadFile(calls)
			if err != nil || string(invocations) != "xx" {
				t.Fatalf("want two Git processes: %q %v", invocations, err)
			}
			if got.Stats.SourcesScanned != 4 || got.Stats.SourcesEnumerated != 4 || got.Stats.BytesScanned != int64(4*len(outgoingTestItems[0].Value)) || got.Stats.Items != 1 || got.Stats.Patterns == 0 || got.Stats.TotalMS <= 0 {
				t.Fatalf("invalid stats: %+v", got.Stats)
			}
			for _, path := range paths {
				if err := os.WriteFile(filepath.Join(root, path), []byte("rotated-synthetic-value"), 0o600); err != nil {
					t.Fatal(err)
				}
			}
			outgoingGit(t, root, "add", ".")
			got, err = ScanStaged(context.Background(), root, []store.Item{{Name: "rotated", Value: []byte("rotated-synthetic-value")}}, 0, Deps{})
			if err != nil || len(got.Matches) != 3 || got.Matches[0].ItemName != "rotated" {
				t.Fatalf("reused stale index or values: %+v %v", got, err)
			}
		})
	}
}

func TestStagedBatchRetainsMatchesAroundMissingAndOversizedBlobs(t *testing.T) {
	root := newOutgoingRepo(t, "sha1")
	for _, path := range []string{"a-leak", "z-leak"} {
		if err := os.WriteFile(filepath.Join(root, path), outgoingTestItems[0].Value, 0o600); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(root, "oversized"), []byte(strings.Repeat("x", 200)), 0o600); err != nil {
		t.Fatal(err)
	}
	outgoingGit(t, root, "add", ".")
	outgoingGit(t, root, "update-index", "--add", "--cacheinfo", "100644,"+strings.Repeat("a", 40)+",missing")
	got, err := ScanStaged(context.Background(), root, outgoingTestItems, 100, Deps{})
	if err == nil || got.Complete || len(got.Matches) != 2 || len(got.Issues) != 1 || len(got.Skipped) != 1 {
		t.Fatalf("partial batch lost coverage or passed: %+v %v", got, err)
	}
	if got.Stats.SourcesEnumerated != 4 || got.Stats.SourcesScanned != 2 || got.Stats.Issues != 1 || got.Stats.Skipped != 1 {
		t.Fatalf("partial stats: %+v", got.Stats)
	}
}

func TestScanStatsMatchActualContentAcrossModes(t *testing.T) {
	root := newOutgoingRepo(t, "sha1")
	tip := outgoingCommit(t, root, "leak", string(outgoingTestItems[0].Value), "base")
	working, err := Scan(context.Background(), root, outgoingTestItems, 0, Deps{})
	if err != nil || working.Stats.SourcesScanned != 1 || working.Stats.BytesScanned != int64(len(outgoingTestItems[0].Value)) {
		t.Fatalf("working stats: %+v %v", working, err)
	}
	outgoing, err := ScanOutgoing(context.Background(), root, outgoingTestItems, 0, []RefUpdate{{"HEAD", tip, "refs/heads/main", strings.Repeat("0", 40)}})
	if err != nil || outgoing.Stats.SourcesScanned != 3 || outgoing.Stats.BytesScanned <= working.Stats.BytesScanned || outgoing.Stats.Items != 1 || outgoing.Stats.TotalMS <= 0 {
		t.Fatalf("outgoing stats: %+v %v", outgoing, err)
	}
}

func TestStagedBatchRejectsUnmergedAndGitlinkEntries(t *testing.T) {
	root := newOutgoingRepo(t, "sha1")
	tip := outgoingCommit(t, root, "conflict", "base", "base")
	blob := outgoingGit(t, root, "rev-parse", "HEAD:conflict")
	cmd := exec.Command("git", "-C", root, "update-index", "--index-info")
	cmd.Stdin = strings.NewReader("0 " + strings.Repeat("0", 40) + "\tconflict\n100644 " + blob + " 1\tconflict\n100644 " + blob + " 2\tconflict\n100644 " + blob + " 3\tconflict\n")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("create unmerged index: %s %v", out, err)
	}
	outgoingGit(t, root, "update-index", "--add", "--cacheinfo", "160000,"+tip+",submodule")
	outgoingGit(t, root, "config", "diff.ignoreSubmodules", "all")
	if err := os.WriteFile(filepath.Join(root, "leak"), outgoingTestItems[0].Value, 0o600); err != nil {
		t.Fatal(err)
	}
	outgoingGit(t, root, "add", "leak")
	got, err := ScanStaged(context.Background(), root, outgoingTestItems, 0, Deps{})
	if err == nil || got.Complete || len(got.Matches) != 1 || len(got.Issues) != 2 {
		t.Fatalf("unscannable entries silently passed: %+v %v", got, err)
	}
}
